In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import load_breast_cancer
breast_cancer = load_breast_cancer()
df = pd.DataFrame(breast_cancer.data, columns=breast_cancer.feature_names)
df.head(3)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   
2        19.69         21.25           130.0     1203.0          0.10960   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33            184.6   
1                 0.05667  ...         24.99          23.41            158.8   
2                 0.05999  ...         23.57          25.53            152.5   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  

[3 rows x 30 columns]

In [4]:
from sklearn.preprocessing import StandardScaler
breast_cancer_std = StandardScaler().fit_transform(breast_cancer.data)
breast_cancer_std[:3]

array([[ 1.09706398e+00, -2.07333501e+00,  1.26993369e+00,
         9.84374905e-01,  1.56846633e+00,  3.28351467e+00,
         2.65287398e+00,  2.53247522e+00,  2.21751501e+00,
         2.25574689e+00,  2.48973393e+00, -5.65265059e-01,
         2.83303087e+00,  2.48757756e+00, -2.14001647e-01,
         1.31686157e+00,  7.24026158e-01,  6.60819941e-01,
         1.14875667e+00,  9.07083081e-01,  1.88668963e+00,
        -1.35929347e+00,  2.30360062e+00,  2.00123749e+00,
         1.30768627e+00,  2.61666502e+00,  2.10952635e+00,
         2.29607613e+00,  2.75062224e+00,  1.93701461e+00],
       [ 1.82982061e+00, -3.53632408e-01,  1.68595471e+00,
         1.90870825e+00, -8.26962447e-01, -4.87071673e-01,
        -2.38458552e-02,  5.48144156e-01,  1.39236330e-03,
        -8.68652457e-01,  4.99254601e-01, -8.76243603e-01,
         2.63326966e-01,  7.42401948e-01, -6.05350847e-01,
        -6.92926270e-01, -4.40780058e-01,  2.60162067e-01,
        -8.05450380e-01, -9.94437403e-02,  1.80592744e+

### 2차원으로 축소

In [24]:
from sklearn.decomposition import PCA
pca2 = PCA(n_components=2)
breast_cancer_pca2 = pca2.fit_transform(breast_cancer_std)
breast_cancer_pca2[:3]

array([[ 9.19283683,  1.94858307],
       [ 2.3878018 , -3.76817174],
       [ 5.73389628, -1.0751738 ]])

In [27]:
pca2.explained_variance_ratio_

array([0.44272026, 0.18971182])

### 5차원으로 축소

In [25]:
pca5 = PCA(n_components=5)
breast_cancer_pca5 = pca5.fit_transform(breast_cancer_std)
breast_cancer_pca5[:3]

array([[ 9.19283683,  1.94858304, -1.12316742,  3.63373604, -1.19509868],
       [ 2.3878018 , -3.76817172, -0.52929173,  1.11826027,  0.62176691],
       [ 5.73389628, -1.0751738 , -0.55174785,  0.91208346, -0.17708403]])

In [26]:
pca5.explained_variance_ratio_

array([0.44272026, 0.18971182, 0.09393163, 0.06602135, 0.05495768])

### 10차원으로 축소

In [28]:
pca10 = PCA(n_components=10)
breast_cancer_pca10 = pca10.fit_transform(breast_cancer_std)
breast_cancer_pca10[:3]

array([[ 9.19283683,  1.94858307, -1.12316616,  3.63373093, -1.19511017,
         1.41142453,  2.15936881, -0.39839905, -0.15713793, -0.87736602],
       [ 2.3878018 , -3.76817174, -0.52929269,  1.11826384,  0.62177502,
         0.02865629,  0.01335846,  0.24098001, -0.71189313,  1.10697835],
       [ 5.73389628, -1.0751738 , -0.55174759,  0.91208268, -0.17708592,
         0.54145217, -0.66816631,  0.09737923,  0.02406209,  0.45427763]])

In [10]:
pca10.explained_variance_ratio_

array([0.44272026, 0.18971182, 0.09393163, 0.06602135, 0.05495768,
       0.04024522, 0.02250734, 0.01588724, 0.01389649, 0.01168978])

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [12]:
# 원본
X_train, X_test, y_train, y_test = train_test_split(
    breast_cancer.data, breast_cancer.target, stratify=breast_cancer.target, random_state=2021
)
rfc = RandomForestClassifier(random_state=2021)
rfc.fit(X_train, y_train)
rfc.score(X_test, y_test)

0.9790209790209791

In [29]:
# 2차원
X_train, X_test, y_train, y_test = train_test_split(
    breast_cancer_pca2, breast_cancer.target, stratify=breast_cancer.target, random_state=2021
)
rfc = RandomForestClassifier(random_state=2021)
rfc.fit(X_train, y_train)
rfc.score(X_test, y_test)

0.9440559440559441

In [30]:
# 5차원
X_train, X_test, y_train, y_test = train_test_split(
    breast_cancer_pca5, breast_cancer.target, stratify=breast_cancer.target, random_state=2021
)
rfc = RandomForestClassifier(random_state=2021)
rfc.fit(X_train, y_train)
rfc.score(X_test, y_test)

0.965034965034965

In [31]:
# 10차원
X_train, X_test, y_train, y_test = train_test_split(
    breast_cancer_pca10, breast_cancer.target, stratify=breast_cancer.target, random_state=2021
)
rfc = RandomForestClassifier(random_state=2021)
rfc.fit(X_train, y_train)
rfc.score(X_test, y_test)

0.972027972027972

In [32]:
def pca_accuracy(X, y):
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, stratify=y, random_state=2021
    )
    rfc = RandomForestClassifier(random_state=2021)
    rfc.fit(X_train, y_train)
    score = rfc.score(X_test, y_test)
    return score

In [33]:
for n in [2,4,6]:
    pca = PCA(n_components=n)
    breast_cancer_pca = pca.fit_transform(breast_cancer_std)
    explained = sum(pca.explained_variance_ratio_)
    acc = pca_accuracy(breast_cancer_pca, breast_cancer.target)
    print(f'PCA {n} 설명력-{explained:.4f} 정확도: {acc:.4f}')

PCA 2 설명력-0.6324 정확도: 0.9441
PCA 4 설명력-0.7924 정확도: 0.9371
PCA 6 설명력-0.8876 정확도: 0.9650
